org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.21.2)
neo_version=21.1.219
loader_version_range=[1,)

mod_id=minego
mod_name=MineGO
mod_version=1.0.0
mod_group_id=com.nukateam
mod_authors=Dayton, Jetug
mod_license=All Rights Reserved
mod_description="Adds guns and skins from CS:GO"

registrate_version = MC1.21-1.3.0+67
jei_version=15.2.0.27